// @vitest-environment jsdom

import {
  cleanup,
  fireEvent,
  render,
  screen,
  waitFor,
} from "@testing-library/react"
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest"

import { AgentArtifactsPanel } from "./AgentArtifactsPanel"
import type { ThreadArtifact } from "@/lib/agents/types"

const mocks = vi.hoisted(() => ({
  downloadThreadArtifact: vi.fn(),
}))

vi.mock("@/lib/agents/api", () => ({
  agentsApi: {
    downloadThreadArtifact: mocks.downloadThreadArtifact,
  },
}))

const artifacts: Array<ThreadArtifact> = [
  {
    id: "older",
    fileName: "notes.md",
    mimeType: "text/markdown",
    sizeBytes: 1024,
    sha256: "a".repeat(64),
    createdAt: "2026-07-16T08:00:00Z",
    expiresAt: "2026-08-16T08:00:00Z",
  },
  {
    id: "newer",
    fileName: "leverage-edu-report.html",
    mimeType: "text/html",
    sizeBytes: 78_310,
    sha256: "b".repeat(64),
    createdAt: "2026-07-17T08:00:00Z",
    expiresAt: "2026-08-17T08:00:00Z",
  },
]

function renderPanel(
  overrides: Partial<React.ComponentProps<typeof AgentArtifactsPanel>> = {}
) {
  const props: React.ComponentProps<typeof AgentArtifactsPanel> = {
    threadId: "thread-1",
    artifacts,
    isLoading: false,
    loadError: null,
    onRetryLoad: vi.fn(),
    ...overrides,
  }
  return { ...render(<AgentArtifactsPanel {...props} />), props }
}

describe("AgentArtifactsPanel", () => {
  beforeEach(() => {
    mocks.downloadThreadArtifact.mockReset()
    vi.stubGlobal("URL", {
      ...URL,
      createObjectURL: vi.fn(() => "blob:artifact"),
      revokeObjectURL: vi.fn(),
    })
    vi.spyOn(HTMLAnchorElement.prototype, "click").mockImplementation(() => {})
  })

  afterEach(() => {
    cleanup()
    vi.restoreAllMocks()
    vi.unstubAllGlobals()
  })

  it("lists newest files first with accessible download controls", () => {
    const { container } = renderPanel()
    const names = Array.from(
      container.querySelectorAll("li p:first-of-type")
    ).map((node) => node.textContent)

    expect(names).toEqual(["leverage-edu-report.html", "notes.md"])
    expect(screen.getByText("HTML · 76.5 KB", { exact: false })).not.toBeNull()
    expect(
      screen.getByRole("button", {
        name: "Download leverage-edu-report.html",
      })
    ).not.toBeNull()
  })

  it("downloads the selected artifact using the server filename", async () => {
    mocks.downloadThreadArtifact.mockResolvedValueOnce({
      blob: new Blob(["report"]),
      filename: "final-report.html",
    })
    renderPanel()

    fireEvent.click(
      screen.getByRole("button", {
        name: "Download leverage-edu-report.html",
      })
    )

    await waitFor(() =>
      expect(mocks.downloadThreadArtifact).toHaveBeenCalledWith(
        "thread-1",
        "newer",
        "leverage-edu-report.html"
      )
    )
    expect(URL.createObjectURL).toHaveBeenCalledOnce()
    expect(URL.revokeObjectURL).toHaveBeenCalledWith("blob:artifact")
  })

  it("shows a per-file error and lets the user retry", async () => {
    mocks.downloadThreadArtifact
      .mockRejectedValueOnce(new Error("artifact unavailable"))
      .mockResolvedValueOnce({
        blob: new Blob(["report"]),
        filename: "leverage-edu-report.html",
      })
    renderPanel()

    fireEvent.click(
      screen.getByRole("button", {
        name: "Download leverage-edu-report.html",
      })
    )
    expect((await screen.findByRole("alert")).textContent).toContain(
      "Download failed: artifact unavailable"
    )

    fireEvent.click(
      screen.getByRole("button", {
        name: "Retry downloading leverage-edu-report.html",
      })
    )
    await waitFor(() =>
      expect(mocks.downloadThreadArtifact).toHaveBeenCalledTimes(2)
    )
    await waitFor(() => expect(screen.queryByRole("alert")).toBeNull())
  })

  it("renders load, empty, and retry states", () => {
    const retry = vi.fn()
    const { rerender } = renderPanel({ artifacts: [], isLoading: true })
    expect(
      screen.getByRole("status", { name: "Loading generated files" })
    ).not.toBeNull()

    rerender(
      <AgentArtifactsPanel
        threadId="thread-1"
        artifacts={[]}
        isLoading={false}
        onRetryLoad={retry}
      />
    )
    expect(
      screen.getByText("Files generated by this agent will appear here.")
    ).not.toBeNull()

    rerender(
      <AgentArtifactsPanel
        threadId="thread-1"
        artifacts={[]}
        isLoading={false}
        loadError="network failed"
        onRetryLoad={retry}
      />
    )
    fireEvent.click(screen.getByRole("button", { name: "Retry" }))
    expect(retry).toHaveBeenCalledOnce()
  })
})
